Fix bug with exception handling
The msg must be converted to a string as it is a ctypes string in
__str__ otherwise we get a

TypeError: __str__ returned non-string (type int)